FROM node:12-alpine

# Set working directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install

RUN npm install --quiet -g serve

# Copy the contents of the project to the image
COPY . .

RUN npm run build

EXPOSE $PORT
CMD serve -p $PORT -s dist
